// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCLRnBBKkEBDgDrhDXzyKnAk4yrDWjlFg',
    appId: '1:1035725202291:web:91846cbb5e9b708cb9db06',
    messagingSenderId: '1035725202291',
    projectId: 'think-code-hrm',
    authDomain: 'think-code-hrm.firebaseapp.com',
    storageBucket: 'think-code-hrm.firebasestorage.app',
    measurementId: 'G-BZMYC67DJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWAMcLs1xMUYXvfLTG1b98y_ZRjhl01Ec',
    appId: '1:1035725202291:android:1b87cc1b8de03cc8b9db06',
    messagingSenderId: '1035725202291',
    projectId: 'think-code-hrm',
    storageBucket: 'think-code-hrm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDELAZ7IP8ZDT1IEqwwxuMwjUBFTx7iqkc',
    appId: '1:1035725202291:ios:878963e0dfb724efb9db06',
    messagingSenderId: '1035725202291',
    projectId: 'think-code-hrm',
    storageBucket: 'think-code-hrm.firebasestorage.app',
    iosBundleId: 'com.onuvia.thinkcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDELAZ7IP8ZDT1IEqwwxuMwjUBFTx7iqkc',
    appId: '1:1035725202291:ios:878963e0dfb724efb9db06',
    messagingSenderId: '1035725202291',
    projectId: 'think-code-hrm',
    storageBucket: 'think-code-hrm.firebasestorage.app',
    iosBundleId: 'com.onuvia.thinkcode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCLRnBBKkEBDgDrhDXzyKnAk4yrDWjlFg',
    appId: '1:1035725202291:web:4a5cd16e2d85c430b9db06',
    messagingSenderId: '1035725202291',
    projectId: 'think-code-hrm',
    authDomain: 'think-code-hrm.firebaseapp.com',
    storageBucket: 'think-code-hrm.firebasestorage.app',
    measurementId: 'G-K9M27S9JVF',
  );
}
